## EduStack — Automated Provisioning Vagrantfile
## Run: vagrant up   (provisions all 5 VMs automatically)
## Author: Samson Olanipekun (github.com/Reich-imperial)

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false

  config.hostmanager.enabled     = true
  config.hostmanager.manage_host = true

  ## ── Database VM (MariaDB) ───────────────────────────────────────────────────
  config.vm.define "db01" do |db01|
    db01.vm.box      = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network  "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
      vb.name   = "edustack-db01"
    end
    db01.vm.provision "shell", path: "mysql.sh"
  end

  ## ── Memcached VM ────────────────────────────────────────────────────────────
  config.vm.define "mc01" do |mc01|
    mc01.vm.box      = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network  "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
      vb.name   = "edustack-mc01"
    end
    mc01.vm.provision "shell", path: "memcache.sh"
  end

  ## ── RabbitMQ VM ─────────────────────────────────────────────────────────────
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box      = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network  "private_network", ip: "192.168.56.16"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
      vb.name   = "edustack-rmq01"
    end
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end

  ## ── Tomcat (Application Server) VM ─────────────────────────────────────────
  config.vm.define "app01" do |app01|
    app01.vm.box      = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vm.network  "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "800"
      vb.name   = "edustack-app01"
    end
    app01.vm.provision "shell", path: "tomcat.sh"
  end

  ## ── Nginx (Web / Reverse Proxy) VM ──────────────────────────────────────────
  config.vm.define "web01" do |web01|
    web01.vm.box      = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network  "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "800"
      vb.name   = "edustack-web01"
    end
    web01.vm.provision "shell", path: "nginx.sh"
  end

end
